import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { Enseignant } from '../../enseignant.model';
import { Offre } from '../../offre.model';
import { Router } from '@angular/router';
import { query } from 'express';

@Component({
  selector: 'app-find-offre',
  standalone: true,
  imports: [CommonModule,],
  templateUrl: './find-offre.component.html',
  styleUrl: './find-offre.component.css'
})
export class FindOffreComponent {
  offres :Offre[]=
  [
   {   
    id_offre:"kjdsk",    
    offre: "professeur pc",
    niveau: "Collège",
    lieu: "Baye bouki",
    departement : "Baye leuk",
    region: "Kolda",
    date_limite: '',
    diplome_exige: "Licence 3",
    type_de_contrat: "CDI", 
  },
  {   
    id_offre:"kjdsk",    
    offre: "professeur pc",
    niveau: "Collège",
    lieu: "Baye bouki",
    departement : "Baye leuk",
    region: "Kolda",
    date_limite: '',
    diplome_exige: "Licence 3",
    type_de_contrat: "CDI", 
  },
  {   
    id_offre:"kjdsk",    
    offre: "professeur pc",
    niveau: "Collège",
    lieu: "Baye bouki",
    departement : "Baye leuk",
    region: "Kolda",
    date_limite: '',
    diplome_exige: "Licence 3",
    type_de_contrat: "CDI", 
  },
  {   
    id_offre:"kjdsk",    
    offre: "professeur pc",
    niveau: "Collège",
    lieu: "Baye bouki",
    departement : "Baye leuk",
    region: "Kolda",
    date_limite: '',
    diplome_exige: "Licence 3",
    type_de_contrat: "CDI", 
  },
  {   
    id_offre:"kjdsk",    
    offre: "professeur pc",
    niveau: "Collège",
    lieu: "Baye bouki",
    departement : "Baye leuk",
    region: "Kolda",
    date_limite: '',
    diplome_exige: "Licence 3",
    type_de_contrat: "CDI", 
  },
  {   
    id_offre:"kjdsk",    
    offre: "professeur pc",
    niveau: "Collège",
    lieu: "Baye bouki",
    departement : "Baye leuk",
    region: "Kolda",
    date_limite: '',
    diplome_exige: "Licence 3",
    type_de_contrat: "CDI", 
  },
  {   
    id_offre:"kjdsk",    
    offre: "professeur pc",
    niveau: "Collège",
    lieu: "Baye bouki",
    departement : "Baye leuk",
    region: "Kolda",
    date_limite: '',
    diplome_exige: "Licence 3",
    type_de_contrat: "CDI", 
  },
  {   
    id_offre:"kjdsk",    
    offre: "professeur pc",
    niveau: "Collège",
    lieu: "Baye bouki",
    departement : "Baye leuk",
    region: "Kolda",
    date_limite: '',
    diplome_exige: "Licence 3",
    type_de_contrat: "CDI", 
  },
  {   
    id_offre:"kjdsk",    
    offre: "professeur pc",
    niveau: "Collège",
    lieu: "Baye bouki",
    departement : "Baye leuk",
    region: "Kolda",
    date_limite: '',
    diplome_exige: "Licence 3",
    type_de_contrat: "CDI", 
  }, {   
    id_offre:"kjdsk",    
    offre: "professeur pc",
    niveau: "Collège",
    lieu: "Baye bouki",
    departement : "Baye leuk",
    region: "Kolda",
    date_limite: '',
    diplome_exige: "Licence 3",
    type_de_contrat: "CDI", 
  },
  {   
    id_offre:"kjdsk",    
    offre: "professeur pc",
    niveau: "Collège",
    lieu: "Baye bouki",
    departement : "Baye leuk",
    region: "Kolda",
    date_limite: '',
    diplome_exige: "Licence 3",
    type_de_contrat: "CDI", 
  },
  {   
    id_offre:"kjdsk",    
    offre: "professeur pc",
    niveau: "Collège",
    lieu: "Baye bouki",
    departement : "Baye leuk",
    region: "Kolda",
    date_limite: '',
    diplome_exige: "Licence 3",
    type_de_contrat: "CDI", 
  }, {   
    id_offre:"kjdsk",    
    offre: "professeur pc",
    niveau: "Collège",
    lieu: "Baye bouki",
    departement : "Baye leuk",
    region: "Kolda",
    date_limite: '',
    diplome_exige: "Licence 3",
    type_de_contrat: "CDI", 
  },
  {   
    id_offre:"kjdsk",    
    offre: "professeur pc",
    niveau: "Collège",
    lieu: "Baye bouki",
    departement : "Baye leuk",
    region: "Kolda",
    date_limite: '',
    diplome_exige: "Licence 3",
    type_de_contrat: "CDI", 
  },
  {   
    id_offre:"kjdsk",    
    offre: "professeur pc",
    niveau: "Collège",
    lieu: "Baye bouki",
    departement : "Baye leuk",
    region: "Kolda",
    date_limite: '',
    diplome_exige: "Licence 3",
    type_de_contrat: "CDI", 
  },
  ]
  constructor(private router :Router){}
  onSelect(offre: Offre){
    this.router.navigate(['/offre-description'],{queryParams: {   
      id_offre:offre.id_offre,    
      offre: offre.offre,
      niveau: offre.niveau,
      lieu: offre.lieu,
      departement : offre.departement,
      region: offre.region,
      date_limite: offre.date_limite,
      diplome_exige: offre.diplome_exige,
      type_de_contrat: offre.type_de_contrat, 
    },})
  }

}
